(require 'cask "/usr/local/Cellar/cask/0.7.2/cask.el")
(cask-initialize)
(require 'pallet)
(pallet-mode t)
(add-to-list 'load-path "/Users/sz/.emacs.d/custom")
(load "00common-setup.el")
(load "01ruby.el")
(load "03scala.el")
;;(load "02ansi-term.el")
;;(put 'upcase-region 'disabled nil)

